server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-Service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: cliente
          uri: lb://CLIENTE
          predicates:
            - Path=/api/clientes/**
        - id: productos
          uri: lb://PRODUCTOS
          predicates:
            - Path=/api/productos/**
        - id: productoArriendo
          uri: lb://PRODUCTOARRIENDO
          predicates:
            - Path=/api/productoArriendo/**
        - id: pedidos
          uri: lb://PEDIDOS
          predicates:
            - Path=/api/pedidos/**
        - id: arriendo
          uri: lb://ARRIENDO
          predicates:
            - Path=/api/arriendos/**
        - id: devolucion
          uri: lb://DEVOLUCION
          predicates:
            - Path=/api/devoluciones/**
        - id: reclamos
          uri: lb://RECLAMOS
          predicates:
            - Path=/api/reclamos/**
        - id: recepcionArriendo
          uri: lb://RECEPCIONARRIENDO
          predicates:
            - Path=/api/recepcionArriendo/**

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include:  health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8791/eureka/}
  instance:
    prefer-ip-address: true